coverage:
  status:
    patch:
      default:
        target: 100%
    project:
      default:
        target: 75% # the required coverage value
        threshold: 1% # the leniency in hitting the target
